# Arquivo de Configuração de Tema do Streamlit

[theme]
# Cor primária (usada em botões, sliders, etc.)
primaryColor="#004A8F"  # Exemplo: um tom de azul

backgroundColor="#FFFFFF"

secondaryBackgroundColor="#F0F2F6"

textColor="#31333F"

font="sans serif"
